config/routes.rb
Rails.application.routes.draw do
  resources :productos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/", to: "productos#index"
  get "/productos/new", to: "productos#new"
  post "/productos", to: "productos#create"
  delete "/productos/:id", to: "productos#destroy"
  get "/productos/:id/edit", to: "productos#edit"
  patch "/productos/:id", to: "productos#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController

    def index
        @productos = Producto.all
    end

    def destroy
        @productos = Producto.find(params[:id])
        if @productos.present?
            @productos.destroy
        end
        redirect_to "/"
    end

    def show 
        @productos = Producto.find(params[:id])
    end 

    def new 
        @productos = Producto.new
    end

    def create   
        @busqueda = Producto.find_by(codigo: productos_params[:codigo])

        if @busqueda.present?
            respond_to do |format|
                format.html { redirect_to "/productos/new", notice: "ERROR: Código duplicado" }
            end
        else
            @productos = Producto.new(productos_params)
            if @productos.save
                redirect_to "/"
            else
                render :new #redirect_to "/productos/new"
            end
        end
    end

    def edit 
        @productos = Producto.find(params[:id])
    end

    def update 
        @productos = Producto.find(params[:id])
        if @productos.update(productos_params)
            redirect_to "/" #productos_path
        else
            render :edit
        end
    end

    private 
        def productos_params
            params.require(:producto).permit(:codigo, :nombre, :descripcion, :precio)
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Micrudsinscaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "miestilo", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productos/edit.html.erb
<h1>Edición de productos</h1>

<%= form_for @productos do |f| %>

<div>
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
</div>

<div>
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
</div>

<div>
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
</div>

<div>
    <%= f.label :precio %>
    <%= f.number_field :precio %>
</div>

<div>
    <%= f.submit %>
</div>

<% end %>

app/views/productos/index.html.erb
<h1>Mostrar productos</h1>

<%=link_to "CREAR NUEVO PRODUCTO", "/productos/new"%>

<br /><br />

<table border="1">

    <tr>
        <thead>
            <th>Id</th>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>ACCIÓN</th>
        </thead>
    </tr>
    
    <%@productos.each do |p|%>   
        <tr>
            <td><%=p.id%></td>
            <td><%=p.codigo%></td>
            <td><%=p.nombre%></td>
            <td><%=p.descripcion%></td>
            <td><%=p.precio%></td>
            <td>
                <%= link_to "Eliminar", p, "data-method"=>:delete %>
                <%= link_to "Modificar", edit_producto_path(p) %>
            </td>
        </tr>
    <%end%>

</table>

app/views/productos/new.html.erb
<h1>Creación de productos</h1>


<%=form_for @productos do |f|%>

<div>
    <%=f.label :codigo%>
    <%=f.text_field :codigo%>
</div>

<div>
    <%=f.label :nombre%>
    <%=f.text_field :nombre%>
</div>

<div>
    <%=f.label :descripcion%>
    <%=f.text_area :descripcion%>
</div>

<div>
    <%=f.label :precio%>
    <%=f.number_field :precio%>
</div>

<div>
    <%=f.submit%>
</div>


<%end%>

app/views/productos/show.html.erb
<table border="1">
    <tr>
        <thead>
            <th>Id</th>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Precio</th>
        </thead>
    </tr>
    <tr>
        <td><%=@productos.id%></td>
        <td><%=@productos.codigo%></td>
        <td><%=@productos.nombre%></td>
        <td><%=@productos.descripcion%></td>
        <td><%=@productos.precio%></td>
    </tr>
</table>

<br /><br />

<%= link_to "Volver atrás", "/" %>

<br /><br />

<%= button_to "Confirmar Eliminación", @productos, method: :delete %>